<a href="https://colab.research.google.com/github/TarunaSahu/hello_world/blob/main/naviebyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
data=pandas.read_csv("Churn Modeling.csv")

In [ ]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
Y=data["Exited"]
X=data.drop(columns=['RowNumber','CustomerId','Surname','Exited'])

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
X["Geography"]=Le.fit_transform(X["Geography"])
X["Gender"]=Le.fit_transform(X["Gender"])

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  int64  
 2   Gender           10000 non-null  int64  
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(8)
memory usage: 781.4 KB


In [ ]:
import numpy
numpy.random.seed(2000)

In [ ]:
from sklearn.model_selection import train_test_split
x_trg,x_test,y_trg,y_test=train_test_split(X,Y,test_size=0.2)


In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model=GaussianNB()

In [ ]:
model.fit(x_trg,y_trg)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
ans=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix(ans,y_test)

array([[1513,  386],
       [  64,   37]])

In [ ]:
accuracy_score(ans,y_test)

0.775

In [ ]:
model11=GaussianNB(var_smoothing=1e-10)
model11.fit(x_trg,y_trg)
ans11=model11.predict(x_test)
print(confusion_matrix(ans11,y_test))
print(accuracy_score(ans11,y_test))


[[1527  363]
 [  50   60]]
0.7935


In [ ]:
from sklearn.linear_model import LogisticRegression
lmodel=LogisticRegression()
lmodel.fit(x_trg,y_trg)
result=lmodel.predict(x_test)

In [ ]:
confusion_matrix(result,y_test)

array([[1541,  399],
       [  36,   24]])

In [ ]:
accuracy_score(result,y_test)

0.7825

In [ ]:
#svm
from sklearn.svm import LinearSVC

In [ ]:
model3=LinearSVC()
model3.fit(x_trg,y_trg)
ans3=model3.predict(x_test)
print(confusion_matrix(ans3,y_test))
print(accuracy_score(ans3,y_test))

[[   7    2]
 [1570  421]]
0.214


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [ ]:
model33=LinearSVC(loss='hinge',C=10,max_iter=5000)
model33.fit(x_trg,y_trg)
ans33=model33.predict(x_test)
print(confusion_matrix(ans33,y_test))
print(accuracy_score(ans33,y_test))

[[1576  422]
 [   1    1]]
0.7885


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
mydict={'C':[1,10,100],'max_iter':[3000,5000,8000]}

In [ ]:
model1=LinearSVC()

In [ ]:
gridmodel=GridSearchCV(estimator=model1,param_grid=mydict,cv=3)
gridmodel.fit(x_trg,y_trg)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarn

GridSearchCV(cv=3, error_score=nan,
             estimator=LinearSVC(C=1.0, class_weight=None, dual=True,
                                 fit_intercept=True, intercept_scaling=1,
                                 loss='squared_hinge', max_iter=1000,
                                 multi_class='ovr', penalty='l2',
                                 random_state=None, tol=0.0001, verbose=0),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 100], 'max_iter': [3000, 5000, 8000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)